language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=restaurant,user manage.py test

after_script:
  - coveralls

env:
  global:
    - secure: XUhyh97/69EJ/7E6/Sf3pb1DhmFkgqdUaTZXk+gbs7SefVbSVhadZetCbIrnOmG2dru9kPqabzoTY2X6UUoAyOiqZrBxNKjXnjpILbe89rshPqIdvcRMYM6WdUbzMV3VucnWBCctDu/6XVHCCLVkQLMafzOC34m4l9vbyAwVLdRF/D/ZjV4Am//hMC8SALxlzNNquKGPpuWjw/xNpjWP0kcbH19DnaW/4Xo0TMdonhIB79d6XFKxXxcvJ/O1Zg2qLIh/XjL3dlqdwORWfpN551YKL7iZXSjfQPBau3t637BoN+XNojFMAD9VIeGJ8woWRh0zvILIRvS0Pf+CGXVht+q8Z0HOUD6IIqxOuxOxa9d4iLnxZ4SAO+0EDBGSFXtgcVX542412CL5aU1nBh3UConc27EYTSNjjLxi7wWHhBGBguHVNcHFVeXQ0q2ZKnC3w4kwDAwDhS1K2/6XxCBM5h6yxeHLccPF8DTLh+gX7knEq7GM9Onm8wTBjAqEWHEgciEwMG/P30tTN6m0Y+K3jHlaFNp8amW5vND9KSM0ZtppQ/2uRzbLbKh0nXGZtXCYB23w826NFtR/r5fGcpdOqV1eKdm8LIO3bLLnBgjJ5hNHytPxF2WXyrwHBoT47visjyfEH8Ah50y22o05VkolELYeEr/C+HCp3wEoVoV36sY=
